@GingerMintSoft.DayTimeService.WebApp_HostAddress = http://localhost:5001

POST {{GingerMintSoft.DayTimeService.WebApp_HostAddress}}/bash/send
Content-Type: application/json

{
  "Command": "w 23 0"
}